"""HTML report generation for RouteSim simulation results.

Generates self-contained HTML reports with interactive Plotly charts
comparing algorithm performance across latency, throughput, and fairness.
"""

import json
from pathlib import Path
from typing import List, Any

# HTML template with embedded Plotly CDN
_REPORT_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>RouteSim Report — {title}</title>
    <script src="https://cdn.plot.ly/plotly-2.27.0.min.js"></script>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
               background: #f5f5f5; color: #333; line-height: 1.6; }}
        .container {{ max-width: 1200px; margin: 0 auto; padding: 20px; }}
        h1 {{ text-align: center; margin: 20px 0; color: #1a1a2e; }}
        h2 {{ margin: 30px 0 15px; color: #16213e; border-bottom: 2px solid #0f3460; padding-bottom: 5px; }}
        .summary {{ background: white; border-radius: 8px; padding: 20px; margin: 20px 0;
                    box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
        table {{ width: 100%; border-collapse: collapse; margin: 15px 0; }}
        th, td {{ padding: 10px 15px; text-align: right; border-bottom: 1px solid #eee; }}
        th {{ background: #1a1a2e; color: white; text-align: right; }}
        th:first-child, td:first-child {{ text-align: left; }}
        tr:hover {{ background: #f0f0f0; }}
        .chart {{ background: white; border-radius: 8px; padding: 15px; margin: 20px 0;
                  box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
        .grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }}
        @media (max-width: 768px) {{ .grid {{ grid-template-columns: 1fr; }} }}
        .footer {{ text-align: center; margin-top: 40px; color: #999; font-size: 0.85em; }}
    </style>
</head>
<body>
<div class="container">
    <h1>RouteSim Report</h1>

    <div class="summary">
        <h2>Algorithm Comparison</h2>
        <table>
            <thead>
                <tr>
                    <th>Algorithm</th>
                    <th>TTFT P50 (ms)</th>
                    <th>TTFT P99 (ms)</th>
                    <th>E2E P50 (ms)</th>
                    <th>E2E P99 (ms)</th>
                    <th>Req/s</th>
                    <th>Cache Hit %</th>
                    <th>Jain's Index</th>
                </tr>
            </thead>
            <tbody>
                {table_rows}
            </tbody>
        </table>
    </div>

    <div class="grid">
        <div class="chart" id="ttft-chart"></div>
        <div class="chart" id="e2e-chart"></div>
        <div class="chart" id="throughput-chart"></div>
        <div class="chart" id="fairness-chart"></div>
    </div>

    <div class="footer">
        Generated by <strong>RouteSim</strong> — Benchmark LLM routing algorithms without GPUs
    </div>
</div>

<script>
const data = {json_data};

// TTFT comparison
Plotly.newPlot('ttft-chart', [{{
    x: data.map(d => d.algorithm),
    y: data.map(d => d.ttft.p50),
    name: 'P50',
    type: 'bar'
}}, {{
    x: data.map(d => d.algorithm),
    y: data.map(d => d.ttft.p99),
    name: 'P99',
    type: 'bar'
}}], {{
    title: 'Time to First Token (ms)',
    barmode: 'group',
    yaxis: {{ title: 'Latency (ms)' }}
}});

// E2E latency
Plotly.newPlot('e2e-chart', [{{
    x: data.map(d => d.algorithm),
    y: data.map(d => d.end_to_end_latency.p50),
    name: 'P50',
    type: 'bar'
}}, {{
    x: data.map(d => d.algorithm),
    y: data.map(d => d.end_to_end_latency.p99),
    name: 'P99',
    type: 'bar'
}}], {{
    title: 'End-to-End Latency (ms)',
    barmode: 'group',
    yaxis: {{ title: 'Latency (ms)' }}
}});

// Throughput
Plotly.newPlot('throughput-chart', [{{
    x: data.map(d => d.algorithm),
    y: data.map(d => d.requests_per_sec),
    name: 'Requests/sec',
    type: 'bar',
    marker: {{ color: '#2196F3' }}
}}, {{
    x: data.map(d => d.algorithm),
    y: data.map(d => d.total_tokens_per_sec),
    name: 'Tokens/sec',
    type: 'bar',
    yaxis: 'y2',
    marker: {{ color: '#FF9800' }}
}}], {{
    title: 'Throughput',
    yaxis: {{ title: 'Requests/sec', side: 'left' }},
    yaxis2: {{ title: 'Tokens/sec', side: 'right', overlaying: 'y' }},
    barmode: 'group'
}});

// Fairness
Plotly.newPlot('fairness-chart', [{{
    x: data.map(d => d.algorithm),
    y: data.map(d => d.jains_fairness_index),
    type: 'bar',
    marker: {{ color: '#4CAF50' }}
}}], {{
    title: "Jain's Fairness Index",
    yaxis: {{ title: 'Fairness (1.0 = perfect)', range: [0, 1.05] }}
}});
</script>
</body>
</html>"""


def generate_html_report(results: List[Any], output_path: str) -> None:
    """Generate an HTML report from simulation results.

    Args:
        results: List of Results objects (or dicts with the same structure).
        output_path: Path to write the HTML file.
    """
    # Convert results to JSON-serializable format
    json_results = []
    for r in results:
        if hasattr(r, "to_json"):
            json_results.append(json.loads(r.to_json()))
        elif isinstance(r, dict):
            json_results.append(r)
        else:
            json_results.append(r)

    # Build table rows
    rows = []
    for r in json_results:
        rows.append(
            f"<tr>"
            f"<td>{r['algorithm']}</td>"
            f"<td>{r['ttft']['p50']:.1f}</td>"
            f"<td>{r['ttft']['p99']:.1f}</td>"
            f"<td>{r['end_to_end_latency']['p50']:.1f}</td>"
            f"<td>{r['end_to_end_latency']['p99']:.1f}</td>"
            f"<td>{r['requests_per_sec']:.1f}</td>"
            f"<td>{r['global_cache_hit_rate'] * 100:.1f}%</td>"
            f"<td>{r['jains_fairness_index']:.4f}</td>"
            f"</tr>"
        )

    title = ", ".join(r["algorithm"] for r in json_results)

    html = _REPORT_TEMPLATE.format(
        title=title,
        table_rows="\n                ".join(rows),
        json_data=json.dumps(json_results),
    )

    Path(output_path).write_text(html)
